# Site settings
title: Technology Resources Worldwide
email: joe@technologyresourcesworlwide.com
description: >- # this means to ignore newlines until "baseurl:"
Doing business since 1998, TRW is aligned with Management Recruiters International (the world’s largest recruiting organization).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rakcloud.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
